// Generated by CoffeeScript 1.7.1
(function() {
  var EventEmitter, screen;

  EventEmitter = require('events').EventEmitter;

  screen = process.atomBinding('screen').screen;

  screen.__proto__ = EventEmitter.prototype;

  module.exports = screen;

}).call(this);
